[package]
name = "stor-port"
version = "0.1.0"
edition = "2021"
description = "Persistent store and transport associated information for the control-plane"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
strum = { workspace = true }
strum_macros = { workspace = true }
serde_json = { workspace = true }
percent-encoding = { workspace = true }
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true, features = ["derive"] }
serde_tuple = { workspace = true }
async-trait = { workspace = true }
dyn-clonable = { workspace = true }
rand = { workspace = true }
tonic = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
tracing = { workspace = true }
prost-types = { workspace = true }

openapi = { workspace = true, features = [ "actix-server", "tower-client", "tower-trace", "tower-client-rls" ] }
platform = { workspace = true }
pstor = { workspace = true }
utils = { workspace = true }
