[package]
name = "grpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "grpc"
path = "src/lib.rs"

[build-dependencies]
tonic-build = { workspace = true }

[dependencies]
tonic = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }

tokio = { workspace = true, features = ["full"] }
stor-port = { workspace = true }
humantime = { workspace = true }
utils = { workspace = true }
rpc = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
tracing-opentelemetry = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-http = { workspace = true }
tracing = { workspace = true }
tower = { workspace = true, features = ["timeout", "util"] }
serde_json = { workspace = true }
events-api = { workspace = true }

[dev-dependencies]
once_cell = { workspace = true }
