apiVersion: openebs.io/v1beta3
kind: DiskPool
spec:
  clusterSize: string
  disks: [] # minItems 0 of type string
  encryptionConfig:
    source:
      secret:
        name: string
  maxExpansion: string
  node: string
  topology:
    labelled: {}
status:
  available: 0
  available_q: "100 GiB"
  capacity: 0
  capacity_q: "100 GiB"
  clusterSize: "100 GiB"
  cr_state: "Creating"
  diskCapacity: "100 GiB"
  encrypted: true
  maxExpandableSize: "100 GiB"
  pool_status: "Unknown" # "Unknown", "Online", "Degraded", "Faulted"
  used: 0
  used_q: "100 GiB"
