[package]
name = "kube-forward"
description = "A low-level Kubernetes forwarding library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kube = { workspace = true, features = ["ws"] }
k8s-openapi = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true, features = ["net"] }
futures = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
shutdown = { workspace = true }
tower = { workspace = true }
hyper = { workspace = true, features = ["client", "http1", "http2"] }
hyper-body = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true, features = ["env-filter"] }
