[package]
name = "deployer-cluster"
version = "1.0.0"
edition = "2021"
description = "Create and Manage local deployer clusters"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true, features = ["full"] }
openapi = { workspace = true, features = ["tower-client", "tower-trace"] }
composer = { workspace = true, default-features = false }
deployer = { workspace = true }
rpc = { workspace = true }
csi-driver = { path = "../../control-plane/csi-driver" }
utils = { workspace = true }
anyhow = { workspace = true }
stor-port = { workspace = true }
clap = { workspace = true, features = ["derive", "env", "string"] }
backtrace = "0.3.74"
etcd-client = { workspace = true }
grpc = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true, features = ["timeout", "util"] }
hyper-util = { workspace = true }
# Tracing
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing-opentelemetry = { workspace = true }
# Open Telemetry
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio-current-thread"] }
opentelemetry-otlp = { workspace = true }
opentelemetry-semantic-conventions = { workspace = true }
