[package]
name = "rpc"
version = "1.0.0"
edition = "2021"

[build-dependencies]
tonic-build = { workspace = true }

[dependencies]
tonic = { workspace = true }
bytes = { workspace = true }
prost = { workspace = true }
prost-derive = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_derive = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
