[package]
name = "k8s-operators"
description = "K8S Operator"
version = "1.0.0"
edition = "2018"

[[bin]]
name = "operator-diskpool"
path = "src/pool/main.rs"
required-features = ["bin"]

[lib]
name = "k8s_operators"
path = "src/lib.rs"

[features]
default = ["rls", "bin"]
bin = ["openapi", "utils", "anyhow", "chrono", "clap", "futures", "snafu", "tokio", "humantime", "tracing"]
rls = ["openapi/tower-client-rls"]
tls = ["openapi/tower-client-tls"]

[dependencies]
# CRD
k8s-openapi = { workspace = true }
kube = { workspace = true, features = ["derive", "runtime"] }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

# Binary
openapi = { workspace = true, default-features = false, features = ["tower-client", "tower-trace"], optional = true }
utils = { workspace = true, optional = true }
anyhow = { workspace = true, optional = true }
chrono = { workspace = true, optional = true }
clap = { workspace = true, features = ["color", "env", "string"], optional = true }
futures = { workspace = true, optional = true }
snafu = { workspace = true, optional = true }
tokio = { workspace = true, features = ["full"], optional = true }
humantime = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
parse-size = { workspace = true }
