#![allow(
    clippy::too_many_arguments,
    clippy::new_without_default,
    non_camel_case_types
)]
/*
 * Mayastor RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

/// BlockDevicePartition : partition information in case where device represents a partition

/// partition information in case where device represents a partition
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct BlockDevicePartition {
    /// partition name
    #[serde(rename = "name")]
    pub name: String,
    /// partition number
    #[serde(rename = "number")]
    pub number: i32,
    /// devname of parent device to which this partition belongs
    #[serde(rename = "parent")]
    pub parent: String,
    /// partition scheme: gpt, dos, ...
    #[serde(rename = "scheme")]
    pub scheme: String,
    /// partition type identifier
    #[serde(rename = "typeid")]
    pub typeid: String,
    /// UUID identifying partition
    #[serde(rename = "uuid")]
    pub uuid: String,
}

impl BlockDevicePartition {
    /// BlockDevicePartition using only the required fields
    pub fn new(
        name: String,
        number: i32,
        parent: String,
        scheme: String,
        typeid: String,
        uuid: String,
    ) -> BlockDevicePartition {
        BlockDevicePartition {
            name,
            number,
            parent,
            scheme,
            typeid,
            uuid,
        }
    }
    /// BlockDevicePartition using all fields
    pub fn new_all(
        name: String,
        number: i32,
        parent: String,
        scheme: String,
        typeid: String,
        uuid: String,
    ) -> BlockDevicePartition {
        BlockDevicePartition {
            name,
            number,
            parent,
            scheme,
            typeid,
            uuid,
        }
    }
}
