#![allow(
    clippy::too_many_arguments,
    clippy::new_without_default,
    non_camel_case_types
)]
/*
 * Mayastor RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

/// Child : Child information

/// Child information
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Child {
    /// current rebuild progress (%)
    #[serde(rename = "rebuildProgress", skip_serializing_if = "Option::is_none")]
    pub rebuild_progress: Option<i32>,
    /// state of the child
    #[serde(rename = "state")]
    pub state: crate::models::ChildState,
    /// uri of the child device
    #[serde(rename = "uri")]
    pub uri: String,
}

impl Child {
    /// Child using only the required fields
    pub fn new(state: crate::models::ChildState, uri: String) -> Child {
        Child {
            rebuild_progress: None,
            state,
            uri,
        }
    }
    /// Child using all fields
    pub fn new_all(
        rebuild_progress: Option<i32>,
        state: crate::models::ChildState,
        uri: String,
    ) -> Child {
        Child {
            rebuild_progress,
            state,
            uri,
        }
    }
}
