#![allow(
    clippy::too_many_arguments,
    clippy::new_without_default,
    non_camel_case_types
)]
/*
 * Mayastor RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

/// CreatePoolBody : Create Pool Body JSON

/// Create Pool Body JSON
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct CreatePoolBody {
    /// disk device paths or URIs to be claimed by the pool
    #[serde(rename = "disks")]
    pub disks: Vec<String>,
}

impl CreatePoolBody {
    /// CreatePoolBody using only the required fields
    pub fn new(disks: Vec<String>) -> CreatePoolBody {
        CreatePoolBody { disks }
    }
    /// CreatePoolBody using all fields
    pub fn new_all(disks: Vec<String>) -> CreatePoolBody {
        CreatePoolBody { disks }
    }
}
