#![allow(
    clippy::too_many_arguments,
    clippy::new_without_default,
    non_camel_case_types,
    unused_imports
)]
/*
 * Mayastor RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

use crate::apis::IntoVec;

/// CreatePoolBody : Create Pool Body JSON

/// Create Pool Body JSON
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct CreatePoolBody {
    /// disk device paths or URIs to be claimed by the pool
    #[serde(rename = "disks")]
    pub disks: Vec<String>,
}

impl CreatePoolBody {
    /// CreatePoolBody using only the required fields
    pub fn new(disks: impl IntoVec<String>) -> CreatePoolBody {
        CreatePoolBody {
            disks: disks.into_vec(),
        }
    }
    /// CreatePoolBody using all fields
    pub fn new_all(disks: impl IntoVec<String>) -> CreatePoolBody {
        CreatePoolBody {
            disks: disks.into_vec(),
        }
    }
}
