#![allow(
    clippy::too_many_arguments,
    clippy::new_without_default,
    non_camel_case_types
)]
/*
 * Mayastor RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

/// CreateReplicaBody : Create Replica Body JSON

/// Create Replica Body JSON
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct CreateReplicaBody {
    #[serde(rename = "share")]
    pub share: crate::models::Protocol,
    /// size of the replica in bytes
    #[serde(rename = "size")]
    pub size: i64,
    /// thin provisioning
    #[serde(rename = "thin")]
    pub thin: bool,
}

impl CreateReplicaBody {
    /// CreateReplicaBody using only the required fields
    pub fn new(share: crate::models::Protocol, size: i64, thin: bool) -> CreateReplicaBody {
        CreateReplicaBody { share, size, thin }
    }
    /// CreateReplicaBody using all fields
    pub fn new_all(share: crate::models::Protocol, size: i64, thin: bool) -> CreateReplicaBody {
        CreateReplicaBody { share, size, thin }
    }
}
