#![allow(
    clippy::too_many_arguments,
    clippy::new_without_default,
    non_camel_case_types
)]
/*
 * Mayastor RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

/// CreateNexusBody : Create Nexus Body JSON

/// Create Nexus Body JSON
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct CreateNexusBody {
    /// replica can be iscsi and nvmf remote targets or a local spdk bdev  (i.e. bdev:///name-of-the-bdev).   uris to the targets we connect to
    #[serde(rename = "children")]
    pub children: Vec<String>,
    /// size of the device in bytes
    #[serde(rename = "size")]
    pub size: i64,
}

impl CreateNexusBody {
    /// CreateNexusBody using only the required fields
    pub fn new(children: Vec<String>, size: i64) -> CreateNexusBody {
        CreateNexusBody { children, size }
    }
    /// CreateNexusBody using all fields
    pub fn new_all(children: Vec<String>, size: i64) -> CreateNexusBody {
        CreateNexusBody { children, size }
    }
}
