#![allow(
    clippy::too_many_arguments,
    clippy::new_without_default,
    non_camel_case_types
)]
/*
 * Mayastor RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

/// ExplicitTopology : volume topology, explicitly selected

/// volume topology, explicitly selected
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct ExplicitTopology {
    /// replicas can only be placed on these nodes
    #[serde(rename = "allowed_nodes")]
    pub allowed_nodes: Vec<String>,
    /// preferred nodes to place the replicas
    #[serde(rename = "preferred_nodes")]
    pub preferred_nodes: Vec<String>,
}

impl ExplicitTopology {
    /// ExplicitTopology using only the required fields
    pub fn new(allowed_nodes: Vec<String>, preferred_nodes: Vec<String>) -> ExplicitTopology {
        ExplicitTopology {
            allowed_nodes,
            preferred_nodes,
        }
    }
    /// ExplicitTopology using all fields
    pub fn new_all(allowed_nodes: Vec<String>, preferred_nodes: Vec<String>) -> ExplicitTopology {
        ExplicitTopology {
            allowed_nodes,
            preferred_nodes,
        }
    }
}
