#![allow(
    clippy::too_many_arguments,
    clippy::new_without_default,
    non_camel_case_types,
    unused_imports
)]
/*
 * Mayastor RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

use crate::apis::IntoVec;

/// ExplicitTopology : volume topology, explicitly selected

/// volume topology, explicitly selected
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct ExplicitTopology {
    /// replicas can only be placed on these nodes
    #[serde(rename = "allowed_nodes")]
    pub allowed_nodes: Vec<String>,
    /// preferred nodes to place the replicas
    #[serde(rename = "preferred_nodes")]
    pub preferred_nodes: Vec<String>,
}

impl ExplicitTopology {
    /// ExplicitTopology using only the required fields
    pub fn new(
        allowed_nodes: impl IntoVec<String>,
        preferred_nodes: impl IntoVec<String>,
    ) -> ExplicitTopology {
        ExplicitTopology {
            allowed_nodes: allowed_nodes.into_vec(),
            preferred_nodes: preferred_nodes.into_vec(),
        }
    }
    /// ExplicitTopology using all fields
    pub fn new_all(
        allowed_nodes: impl IntoVec<String>,
        preferred_nodes: impl IntoVec<String>,
    ) -> ExplicitTopology {
        ExplicitTopology {
            allowed_nodes: allowed_nodes.into_vec(),
            preferred_nodes: preferred_nodes.into_vec(),
        }
    }
}
