#![allow(
    clippy::too_many_arguments,
    clippy::new_without_default,
    non_camel_case_types
)]
/*
 * Mayastor RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

/// NodeTopology : node topology

/// node topology
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct NodeTopology {
    /// exclusive labels
    #[serde(rename = "exclusion")]
    pub exclusion: Vec<String>,
    /// inclusive labels
    #[serde(rename = "inclusion")]
    pub inclusion: Vec<String>,
}

impl NodeTopology {
    /// NodeTopology using only the required fields
    pub fn new(exclusion: Vec<String>, inclusion: Vec<String>) -> NodeTopology {
        NodeTopology {
            exclusion,
            inclusion,
        }
    }
    /// NodeTopology using all fields
    pub fn new_all(exclusion: Vec<String>, inclusion: Vec<String>) -> NodeTopology {
        NodeTopology {
            exclusion,
            inclusion,
        }
    }
}
