#![allow(
    clippy::too_many_arguments,
    clippy::new_without_default,
    non_camel_case_types,
    unused_imports
)]
/*
 * Mayastor RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

use crate::apis::IntoVec;

/// NodeSpec : mayastor storage node information

/// mayastor storage node information
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct NodeSpec {
    /// gRPC endpoint of the mayastor instance
    #[serde(rename = "grpcEndpoint")]
    pub grpc_endpoint: String,
    /// storage node identifier
    #[serde(rename = "id")]
    pub id: String,
}

impl NodeSpec {
    /// NodeSpec using only the required fields
    pub fn new(grpc_endpoint: impl Into<String>, id: impl Into<String>) -> NodeSpec {
        NodeSpec {
            grpc_endpoint: grpc_endpoint.into(),
            id: id.into(),
        }
    }
    /// NodeSpec using all fields
    pub fn new_all(grpc_endpoint: impl Into<String>, id: impl Into<String>) -> NodeSpec {
        NodeSpec {
            grpc_endpoint: grpc_endpoint.into(),
            id: id.into(),
        }
    }
}
