#![allow(
    clippy::too_many_arguments,
    clippy::new_without_default,
    non_camel_case_types,
    unused_imports
)]
/*
 * Mayastor RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

use crate::apis::IntoVec;

/// PoolSpec : User specification of a pool.

/// User specification of a pool.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct PoolSpec {
    /// absolute disk paths claimed by the pool
    #[serde(rename = "disks")]
    pub disks: Vec<String>,
    /// id of the pool
    #[serde(rename = "id")]
    pub id: String,
    /// Pool labels.
    #[serde(rename = "labels")]
    pub labels: Vec<String>,
    /// id of the mayastor instance
    #[serde(rename = "node")]
    pub node: String,
    #[serde(rename = "operation", skip_serializing_if = "Option::is_none")]
    pub operation: Option<crate::models::PoolSpecOperation>,
    #[serde(rename = "state")]
    pub state: crate::models::SpecState,
}

impl PoolSpec {
    /// PoolSpec using only the required fields
    pub fn new(
        disks: impl IntoVec<String>,
        id: impl Into<String>,
        labels: impl IntoVec<String>,
        node: impl Into<String>,
        state: impl Into<crate::models::SpecState>,
    ) -> PoolSpec {
        PoolSpec {
            disks: disks.into_vec(),
            id: id.into(),
            labels: labels.into_vec(),
            node: node.into(),
            operation: None,
            state: state.into(),
        }
    }
    /// PoolSpec using all fields
    pub fn new_all(
        disks: impl IntoVec<String>,
        id: impl Into<String>,
        labels: impl IntoVec<String>,
        node: impl Into<String>,
        operation: impl Into<Option<crate::models::PoolSpecOperation>>,
        state: impl Into<crate::models::SpecState>,
    ) -> PoolSpec {
        PoolSpec {
            disks: disks.into_vec(),
            id: id.into(),
            labels: labels.into_vec(),
            node: node.into(),
            operation: operation.into(),
            state: state.into(),
        }
    }
}
