#![allow(
    clippy::too_many_arguments,
    clippy::new_without_default,
    non_camel_case_types
)]
/*
 * Mayastor RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

/// PoolTopology : pool topology

/// pool topology
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct PoolTopology {
    /// inclusive labels
    #[serde(rename = "inclusion")]
    pub inclusion: Vec<String>,
}

impl PoolTopology {
    /// PoolTopology using only the required fields
    pub fn new(inclusion: Vec<String>) -> PoolTopology {
        PoolTopology { inclusion }
    }
    /// PoolTopology using all fields
    pub fn new_all(inclusion: Vec<String>) -> PoolTopology {
        PoolTopology { inclusion }
    }
}
