#![allow(
    clippy::too_many_arguments,
    clippy::new_without_default,
    non_camel_case_types
)]
/*
 * Mayastor RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

/// ReplicaSpecOwners : Owner Resource

/// Owner Resource
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct ReplicaSpecOwners {
    #[serde(rename = "nexuses")]
    pub nexuses: Vec<uuid::Uuid>,
    #[serde(rename = "volume", skip_serializing_if = "Option::is_none")]
    pub volume: Option<uuid::Uuid>,
}

impl ReplicaSpecOwners {
    /// ReplicaSpecOwners using only the required fields
    pub fn new(nexuses: Vec<uuid::Uuid>) -> ReplicaSpecOwners {
        ReplicaSpecOwners {
            nexuses,
            volume: None,
        }
    }
    /// ReplicaSpecOwners using all fields
    pub fn new_all(nexuses: Vec<uuid::Uuid>, volume: Option<uuid::Uuid>) -> ReplicaSpecOwners {
        ReplicaSpecOwners { nexuses, volume }
    }
}
