#![allow(
    clippy::too_many_arguments,
    clippy::new_without_default,
    non_camel_case_types,
    unused_imports
)]
/*
 * Mayastor RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

use crate::apis::IntoVec;

/// Replica : Replica information

/// Replica information
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Replica {
    /// storage node identifier
    #[serde(rename = "node")]
    pub node: String,
    /// storage pool identifier
    #[serde(rename = "pool")]
    pub pool: String,
    #[serde(rename = "share")]
    pub share: crate::models::Protocol,
    /// size of the replica in bytes
    #[serde(rename = "size")]
    pub size: u64,
    #[serde(rename = "state")]
    pub state: crate::models::ReplicaState,
    /// thin provisioning
    #[serde(rename = "thin")]
    pub thin: bool,
    /// uri usable by nexus to access it
    #[serde(rename = "uri")]
    pub uri: String,
    /// uuid of the replica
    #[serde(rename = "uuid")]
    pub uuid: uuid::Uuid,
}

impl Replica {
    /// Replica using only the required fields
    pub fn new(
        node: impl Into<String>,
        pool: impl Into<String>,
        share: impl Into<crate::models::Protocol>,
        size: impl Into<u64>,
        state: impl Into<crate::models::ReplicaState>,
        thin: impl Into<bool>,
        uri: impl Into<String>,
        uuid: impl Into<uuid::Uuid>,
    ) -> Replica {
        Replica {
            node: node.into(),
            pool: pool.into(),
            share: share.into(),
            size: size.into(),
            state: state.into(),
            thin: thin.into(),
            uri: uri.into(),
            uuid: uuid.into(),
        }
    }
    /// Replica using all fields
    pub fn new_all(
        node: impl Into<String>,
        pool: impl Into<String>,
        share: impl Into<crate::models::Protocol>,
        size: impl Into<u64>,
        state: impl Into<crate::models::ReplicaState>,
        thin: impl Into<bool>,
        uri: impl Into<String>,
        uuid: impl Into<uuid::Uuid>,
    ) -> Replica {
        Replica {
            node: node.into(),
            pool: pool.into(),
            share: share.into(),
            size: size.into(),
            state: state.into(),
            thin: thin.into(),
            uri: uri.into(),
            uuid: uuid.into(),
        }
    }
}
