#![allow(
    clippy::too_many_arguments,
    clippy::new_without_default,
    non_camel_case_types
)]
/*
 * Mayastor RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

/// ReplicaSpec : User specification of a replica.

/// User specification of a replica.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct ReplicaSpec {
    /// Managed by our control plane
    #[serde(rename = "managed")]
    pub managed: bool,
    #[serde(rename = "operation", skip_serializing_if = "Option::is_none")]
    pub operation: Option<crate::models::ReplicaSpecOperation>,
    #[serde(rename = "owners")]
    pub owners: crate::models::ReplicaSpecOwners,
    /// The pool that the replica should live on.
    #[serde(rename = "pool")]
    pub pool: String,
    #[serde(rename = "share")]
    pub share: crate::models::Protocol,
    /// The size that the replica should be.
    #[serde(rename = "size")]
    pub size: i64,
    #[serde(rename = "state")]
    pub state: crate::models::SpecState,
    /// Thin provisioning.
    #[serde(rename = "thin")]
    pub thin: bool,
    /// uuid of the replica
    #[serde(rename = "uuid")]
    pub uuid: uuid::Uuid,
}

impl ReplicaSpec {
    /// ReplicaSpec using only the required fields
    pub fn new(
        managed: bool,
        owners: crate::models::ReplicaSpecOwners,
        pool: String,
        share: crate::models::Protocol,
        size: i64,
        state: crate::models::SpecState,
        thin: bool,
        uuid: uuid::Uuid,
    ) -> ReplicaSpec {
        ReplicaSpec {
            managed,
            operation: None,
            owners,
            pool,
            share,
            size,
            state,
            thin,
            uuid,
        }
    }
    /// ReplicaSpec using all fields
    pub fn new_all(
        managed: bool,
        operation: Option<crate::models::ReplicaSpecOperation>,
        owners: crate::models::ReplicaSpecOwners,
        pool: String,
        share: crate::models::Protocol,
        size: i64,
        state: crate::models::SpecState,
        thin: bool,
        uuid: uuid::Uuid,
    ) -> ReplicaSpec {
        ReplicaSpec {
            managed,
            operation,
            owners,
            pool,
            share,
            size,
            state,
            thin,
            uuid,
        }
    }
}
