#![allow(
    clippy::too_many_arguments,
    clippy::new_without_default,
    non_camel_case_types
)]
/*
 * Mayastor RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

/// ReplicaSpecOperation : Record of the operation in progress

/// Record of the operation in progress
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct ReplicaSpecOperation {
    /// Record of the operation
    #[serde(rename = "operation")]
    pub operation: Operation,
    /// Result of the operation
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<bool>,
}

impl ReplicaSpecOperation {
    /// ReplicaSpecOperation using only the required fields
    pub fn new(operation: Operation) -> ReplicaSpecOperation {
        ReplicaSpecOperation {
            operation,
            result: None,
        }
    }
    /// ReplicaSpecOperation using all fields
    pub fn new_all(operation: Operation, result: Option<bool>) -> ReplicaSpecOperation {
        ReplicaSpecOperation { operation, result }
    }
}

/// Record of the operation
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Operation {
    #[serde(rename = "Create")]
    Create,
    #[serde(rename = "Destroy")]
    Destroy,
    #[serde(rename = "Share")]
    Share,
    #[serde(rename = "Unshare")]
    Unshare,
}

impl Default for Operation {
    fn default() -> Self {
        Self::Create
    }
}
