#![allow(
    clippy::too_many_arguments,
    clippy::new_without_default,
    non_camel_case_types,
    unused_imports
)]
/*
 * Mayastor RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

use crate::apis::IntoVec;

/// ReplicaState : state of the replica

/// state of the replica
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReplicaState {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "online")]
    Online,
    #[serde(rename = "degraded")]
    Degraded,
    #[serde(rename = "faulted")]
    Faulted,
}

impl ToString for ReplicaState {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("unknown"),
            Self::Online => String::from("online"),
            Self::Degraded => String::from("degraded"),
            Self::Faulted => String::from("faulted"),
        }
    }
}

impl Default for ReplicaState {
    fn default() -> Self {
        Self::Unknown
    }
}
