#![allow(
    clippy::too_many_arguments,
    clippy::new_without_default,
    non_camel_case_types
)]
/*
 * Mayastor RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

/// SpecState : Common base state for a resource

/// Common base state for a resource
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SpecState {
    #[serde(rename = "Creating")]
    Creating,
    #[serde(rename = "Created")]
    Created,
    #[serde(rename = "Deleting")]
    Deleting,
    #[serde(rename = "Deleted")]
    Deleted,
}

impl ToString for SpecState {
    fn to_string(&self) -> String {
        match self {
            Self::Creating => String::from("Creating"),
            Self::Created => String::from("Created"),
            Self::Deleting => String::from("Deleting"),
            Self::Deleted => String::from("Deleted"),
        }
    }
}

impl Default for SpecState {
    fn default() -> Self {
        Self::Creating
    }
}
