#![allow(
    clippy::too_many_arguments,
    clippy::new_without_default,
    non_camel_case_types
)]
/*
 * Mayastor RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

/// VolumeSpecOperation : Record of the operation in progress

/// Record of the operation in progress
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct VolumeSpecOperation {
    /// Record of the operation
    #[serde(rename = "operation")]
    pub operation: Operation,
    /// Result of the operation
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<bool>,
}

impl VolumeSpecOperation {
    /// VolumeSpecOperation using only the required fields
    pub fn new(operation: Operation) -> VolumeSpecOperation {
        VolumeSpecOperation {
            operation,
            result: None,
        }
    }
    /// VolumeSpecOperation using all fields
    pub fn new_all(operation: Operation, result: Option<bool>) -> VolumeSpecOperation {
        VolumeSpecOperation { operation, result }
    }
}

/// Record of the operation
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Operation {
    #[serde(rename = "Create")]
    Create,
    #[serde(rename = "Destroy")]
    Destroy,
    #[serde(rename = "Share")]
    Share,
    #[serde(rename = "Unshare")]
    Unshare,
    #[serde(rename = "AddReplica")]
    AddReplica,
    #[serde(rename = "RemoveReplica")]
    RemoveReplica,
    #[serde(rename = "Publish")]
    Publish,
    #[serde(rename = "Unpublish")]
    Unpublish,
}

impl Default for Operation {
    fn default() -> Self {
        Self::Create
    }
}
