#![allow(
    clippy::too_many_arguments,
    clippy::new_without_default,
    non_camel_case_types,
    unused_imports
)]
/*
 * Mayastor RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

use crate::apis::IntoVec;

/// Volume : Volumes   Volume information

/// Volumes   Volume information
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Volume {
    /// array of children nexuses
    #[serde(rename = "children")]
    pub children: Vec<crate::models::Nexus>,
    #[serde(rename = "protocol")]
    pub protocol: crate::models::Protocol,
    /// size of the volume in bytes
    #[serde(rename = "size")]
    pub size: i64,
    #[serde(rename = "state")]
    pub state: crate::models::VolumeState,
    /// name of the volume
    #[serde(rename = "uuid")]
    pub uuid: uuid::Uuid,
}

impl Volume {
    /// Volume using only the required fields
    pub fn new(
        children: impl IntoVec<crate::models::Nexus>,
        protocol: impl Into<crate::models::Protocol>,
        size: impl Into<i64>,
        state: impl Into<crate::models::VolumeState>,
        uuid: impl Into<uuid::Uuid>,
    ) -> Volume {
        Volume {
            children: children.into_vec(),
            protocol: protocol.into(),
            size: size.into(),
            state: state.into(),
            uuid: uuid.into(),
        }
    }
    /// Volume using all fields
    pub fn new_all(
        children: impl IntoVec<crate::models::Nexus>,
        protocol: impl Into<crate::models::Protocol>,
        size: impl Into<i64>,
        state: impl Into<crate::models::VolumeState>,
        uuid: impl Into<uuid::Uuid>,
    ) -> Volume {
        Volume {
            children: children.into_vec(),
            protocol: protocol.into(),
            size: size.into(),
            state: state.into(),
            uuid: uuid.into(),
        }
    }
}
