#![allow(
    clippy::too_many_arguments,
    clippy::new_without_default,
    non_camel_case_types,
    unused_imports
)]
/*
 * Mayastor RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

use crate::apis::IntoVec;

/// VolumeSpec : User specification of a volume.

/// User specification of a volume.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct VolumeSpec {
    /// Optionally used to store custom volume information
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<::std::collections::HashMap<String, String>>,
    /// Number of children the volume should have.
    #[serde(rename = "num_replicas")]
    pub num_replicas: u8,
    #[serde(rename = "operation", skip_serializing_if = "Option::is_none")]
    pub operation: Option<crate::models::VolumeSpecOperation>,
    #[serde(rename = "protocol")]
    pub protocol: crate::models::Protocol,
    /// Size that the volume should be.
    #[serde(rename = "size")]
    pub size: u64,
    #[serde(rename = "status")]
    pub status: crate::models::SpecStatus,
    /// The node where front-end IO will be sent to
    #[serde(rename = "target_node", skip_serializing_if = "Option::is_none")]
    pub target_node: Option<String>,
    /// Volume Id
    #[serde(rename = "uuid")]
    pub uuid: uuid::Uuid,
    #[serde(rename = "topology", skip_serializing_if = "Option::is_none")]
    pub topology: Option<crate::models::Topology>,
    #[serde(rename = "policy")]
    pub policy: crate::models::VolumePolicy,
}

impl VolumeSpec {
    /// VolumeSpec using only the required fields
    pub fn new(
        num_replicas: impl Into<u8>,
        protocol: impl Into<crate::models::Protocol>,
        size: impl Into<u64>,
        status: impl Into<crate::models::SpecStatus>,
        uuid: impl Into<uuid::Uuid>,
        policy: impl Into<crate::models::VolumePolicy>,
    ) -> VolumeSpec {
        VolumeSpec {
            labels: None,
            num_replicas: num_replicas.into(),
            operation: None,
            protocol: protocol.into(),
            size: size.into(),
            status: status.into(),
            target_node: None,
            uuid: uuid.into(),
            topology: None,
            policy: policy.into(),
        }
    }
    /// VolumeSpec using all fields
    pub fn new_all(
        labels: impl Into<Option<::std::collections::HashMap<String, String>>>,
        num_replicas: impl Into<u8>,
        operation: impl Into<Option<crate::models::VolumeSpecOperation>>,
        protocol: impl Into<crate::models::Protocol>,
        size: impl Into<u64>,
        status: impl Into<crate::models::SpecStatus>,
        target_node: impl Into<Option<String>>,
        uuid: impl Into<uuid::Uuid>,
        topology: impl Into<Option<crate::models::Topology>>,
        policy: impl Into<crate::models::VolumePolicy>,
    ) -> VolumeSpec {
        VolumeSpec {
            labels: labels.into(),
            num_replicas: num_replicas.into(),
            operation: operation.into(),
            protocol: protocol.into(),
            size: size.into(),
            status: status.into(),
            target_node: target_node.into(),
            uuid: uuid.into(),
            topology: topology.into(),
            policy: policy.into(),
        }
    }
}
