[package]
name = "rest-plugin"
description = "Rest Plugin"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "rest-plugin"

[lib]
name = "plugin"
path = "./src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["rls"]
rls = ["openapi/tower-client-rls"]

[dependencies]
tracing = { workspace = true }
openapi = { workspace = true, default-features = false, features = ["tower-trace"] }
utils = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
once_cell = { workspace = true }
clap = { workspace = true, features = ["color", "derive", "string"] }
prettytable-rs = { workspace = true }
lazy_static = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
humantime = { workspace = true }
chrono = { workspace = true }
snafu = { workspace = true }
inquire = { workspace = true, default-features = false, features = ["crossterm"] }
itertools = { workspace = true }

[dev-dependencies]
shutdown_hooks = { workspace = true }
deployer-cluster = { workspace = true }
gag = { workspace = true }
