[package]
name = "kube-proxy"
version = "1.0.0"
edition = "2021"
description = "Kubernetes OpenApi Client via k8s-proxy"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["rls"]
rls = ["openapi/tower-client-rls"]
tls = ["openapi/tower-client-tls"]

[dependencies]
kube-forward = { path = "../forward" }
openapi = { workspace = true, default-features = false, features = ["tower-trace"] }
utils = { workspace = true }

kube = { workspace = true, features = ["derive"] }
tower = { workspace = true, features = ["timeout", "util"] }
hyper-util = { workspace = true, features = ["client", "client-legacy", "http1", "http2", "tokio", "service"] }
hyper = { workspace = true, features = ["client", "http1", "http2"] }
hyper-body = { workspace = true }

anyhow = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
