[package]
name = "agents"
description = "Control plane agent"
version = "1.0.0"
edition = "2021"

[lib]
name = "agents"
path = "src/lib.rs"

[[bin]]
name = "core"
path = "src/bin/core/main.rs"

[[test]]
name = "core"
path = "src/bin/core/tests/test.rs"

[[bin]]
name = "jsongrpc"
path = "src/bin/jsongrpc/main.rs"

[[bin]]
name = "agent-ha-node"
path = "src/bin/ha/node/main.rs"

[[bin]]
name = "agent-ha-cluster"
path = "src/bin/ha/cluster/main.rs"

[dependencies]
anyhow = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }
chrono = { workspace = true }
clap = { workspace = true, features = ["color", "derive", "env", "string"] }
tokio = { workspace = true, features = ["full"] }
tonic = { workspace = true }
futures = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
async-trait = { workspace = true }
dyn-clonable = { workspace = true }
snafu = { workspace = true }
humantime = { workspace = true }
state = { workspace = true }
reqwest = { workspace = true }
parking_lot = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
indexmap = { workspace = true }
futures-util = { workspace = true }
crossbeam-queue = { workspace = true }
tower = { workspace = true, features = ["timeout", "util"] }
http = { workspace = true }
hyper-util = { workspace = true }
hyper = { workspace = true, features = ["client", "http1", "http2"] }
opentelemetry = { workspace = true }
tracing = { workspace = true }
nix = { workspace = true, default-features = false }
prost-types = { workspace = true }
url = { workspace = true }
regex = { workspace = true }

grpc = { workspace = true }
shutdown = { workspace = true }
rpc = { workspace = true }
stor-port = { workspace = true }
utils = { workspace = true }
nvmeadm = { workspace = true }
weighted-scoring = { workspace = true }
events-api = { workspace = true }

[target.'cfg(target_os="linux")'.dependencies]
tokio-udev = { workspace = true }

[dev-dependencies]
deployer-cluster = { workspace = true }
events-api = { workspace = true }
url = { workspace = true }
once_cell = { workspace = true }
