[package]
name = "csi-driver"
description = "CSI Driver"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "csi-controller"
path = "src/bin/controller/main.rs"

[[bin]]
name = "csi-node"
path = "src/bin/node/main.rs"

[build-dependencies]
tonic-build = { workspace = true }

[dependencies]
prost = { workspace = true }
prost-types = { workspace = true }
tonic = { workspace = true }

tokio-stream = { workspace = true, features = ["net"] }

anyhow = { workspace = true }
futures = { workspace = true, default-features = false }
humantime = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
rpc = { workspace = true }
grpc = { workspace = true }
tokio = { workspace = true, features = ["full"] }
clap = { workspace = true, features = ["color", "env", "string"] }
nix = { workspace = true, default-features = false, features = ["ioctl", "fs"] }
strum = { workspace = true }
strum_macros = { workspace = true }
heck = { workspace = true }
tracing = { workspace = true }
glob = { workspace = true }
lazy_static = { workspace = true }
serde_json = { workspace = true }
snafu = { workspace = true }
url = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
which = { workspace = true }
k8s-openapi = { workspace = true }
kube = { workspace = true, features = ["runtime", "derive"] }
nvmeadm = { workspace = true }
sysfs = { workspace = true }
stor-port = { workspace = true }
utils = { workspace = true }
shutdown = { workspace = true }
serde = { workspace = true, features = ["derive"] }
parse-size = { workspace = true }

[target.'cfg(target_os="linux")'.dependencies]
udev = { workspace = true }
devinfo = { workspace = true }
sys-mount = { workspace = true, default-features = false }
