#!/usr/bin/env bash

set -e

# Generate the OpenApi client code for the BDD tests.
# The autogenerated code is placed in ../tests/bdd/openapi
./scripts/generate-openapi-bindings-bdd.sh

# Remove the BDD tests for the autogenerated code (we aren't interested in those).
rm -rf tests/bdd/openapi/test

virtualenv --no-setuptools tests/bdd/venv
source ./tests/bdd/venv/bin/activate
pip install -r tests/bdd/requirements.txt

# Configure the environment variables used by the pytests
export PYTHONPATH=$PYTHONPATH:tests/bdd/openapi
export ROOT_DIR="$(dirname "$0")/.."

pytest tests/bdd
