#!/usr/bin/env bash

set -e

SCRIPT_DIR="$(dirname "$0")"
export ROOT_DIR="$SCRIPT_DIR/.."
BDD_TEST_DIR="$ROOT_DIR/tests/bdd"

# build the test dependencies
cargo build --bins

# Generate the OpenApi client code for the BDD tests.
# The autogenerated code is placed in ../tests/bdd/openapi
"$SCRIPT_DIR"/generate-openapi-bindings-bdd.sh

# Remove the BDD tests for the autogenerated code (we aren't interested in those).
rm -rf "$BDD_TEST_DIR"/openapi/test

virtualenv --no-setuptools "$BDD_TEST_DIR"/venv

# Generate gRPC protobuf stubs.
python -m grpc_tools.protoc --proto_path="$ROOT_DIR"/rpc/mayastor-api/protobuf/ --grpc_python_out="$BDD_TEST_DIR" --python_out="$BDD_TEST_DIR" csi.proto

source "$BDD_TEST_DIR"/venv/bin/activate
pip install -r "$BDD_TEST_DIR"/requirements.txt

# Configure the environment variables used by the pytests
export PYTHONPATH=$PYTHONPATH:tests/bdd/openapi

pytest "$BDD_TEST_DIR"
