#!/usr/bin/env bash

set -e

SCRIPTDIR=$(dirname "$0")
TARGET="$SCRIPTDIR/../tests/bdd/openapi"
SPEC="$SCRIPTDIR/../control-plane/rest/openapi-specs/v0_api_spec.yaml"

# Regenerate the bindings only if the rest src changed
check_spec="no"

case "$1" in
    --changes)
        check_spec="yes"
        ;;
esac

if [[ $check_spec = "yes" ]]; then
    git diff --cached --exit-code "$SPEC" 1>/dev/null && exit 0
fi

# Cleanup the existing autogenerated code
if [ ! -d "$TARGET" ]; then
  mkdir -p "$TARGET"
else
  rm -rf "$TARGET"
  mkdir -p "$TARGET"
fi

# Generate a new openapi python client for use by the BDD tests
openapi-generator-cli generate -i "$SPEC" -g python -o "$TARGET"

# If the openapi bindings were modified then fail the check
git diff --exit-code "$TARGET"

