[package]
name = "deployer"
description = "Deployer of control plane and data plane components"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "deployer"
path = "bin/src/deployer.rs"

[lib]
name = "deployer_lib"
path = "src/lib.rs"

[dependencies]
composer = { workspace = true, default-features = false }
stor-port = { workspace = true }
rpc = { workspace = true }
utils = { workspace = true }
grpc = { workspace = true }

clap = { workspace = true, features = ["color", "derive", "env", "string"] }
tokio = { workspace = true, features = ["full"] }
tonic = { workspace = true }
async-trait = { workspace = true }
hyper-util = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
paste = { workspace = true }
humantime = { workspace = true }
reqwest = { workspace = true, default-features = false, features = ["multipart", "query"] }
futures = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tower = { workspace = true, features = ["timeout", "util"] }
events-api = { workspace = true }
anyhow = { workspace = true }
nix = { workspace = true, features = ["signal", "process"] }
