[package]
name = "bundle-sim"
version = "0.1.0"
edition = "2024"

[dependencies]
composer = { workspace = true, default-features = false }
deployer = { workspace = true }
stor-port = { workspace = true }
rpc = { workspace = true }
utils = { workspace = true }
clap = { workspace = true, features = ["color", "derive", "env", "string"] }
tokio = { workspace = true, features = ["full"] }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
anyhow = { workspace = true }
flate2 = { workspace = true }
tar = { workspace = true }
etcd-client = { workspace = true }
serde_json = { workspace = true }
