[package]
name = "pstor-usage"
description = "Persistent Storage Usage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true, features = ["full"] }
openapi = { workspace = true, default-features = false, features = ["tower-client", "tower-trace"] }
deployer-cluster = { workspace = true }
utils = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true, features = ["color", "derive", "env", "string"] }
parse-size = { workspace = true, features = ["std"] }
async-trait = { workspace = true }
etcd-client = { workspace = true }
prettytable-rs = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
itertools = { workspace = true }
