name: ImageBuild CI
on:
  workflow_call:
  push:
    branches:
      - cache
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CI: 1

jobs:
  image-build-test:
    permissions:
      contents: read
      actions: read # optional: detect evicted cache entries upfront
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
      - name: Setup Nix Environment
        uses: ./.github/actions/setup-nix
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test building the release images
        run: ./scripts/release.sh --skip-publish --build-bins
