name: Bors CI
on:
  workflow_call:
  push:
    branches:
      - staging
      - trying
  merge_group:

jobs:
  lint-ci:
    uses: ./.github/workflows/lint.yml
  int-ci:
    uses: ./.github/workflows/unit-int.yml
  bdd-ci:
    uses: ./.github/workflows/bdd.yml
  image-ci:
    uses: ./.github/workflows/image-pr.yml
  bors-ci:
    if: ${{ !cancelled() }}
    needs:
      - lint-ci
      - int-ci
      - bdd-ci
      - image-ci
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            exit 1
          fi
          exit 0
