[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[features]
default = ["rls"]
rls = ["event-publisher/rls-aws-lc-rs"]

[dependencies]
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
tracing-opentelemetry = { workspace = true }
tracing = { workspace = true }

opentelemetry = { workspace = true }

opentelemetry_sdk = { workspace = true, features = ["rt-tokio-current-thread"] }
opentelemetry-otlp = { workspace = true }
opentelemetry-semantic-conventions = { workspace = true }

url = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
heck = { workspace = true }
regex = { workspace = true }

version-info = { path = "../dependencies/version-info", default-features = false }
git-version-macro = { path = "../dependencies/git-version-macro" }
event-publisher = { path = "../dependencies/event-publisher", default-features = false }
tracing-filter = { path = "../dependencies/tracing-filter" }
